# Step 1. Install required libraries



In [ ]:
!pip install hnswlib transformers sentence-transformers

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 1.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 101.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 68.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 45.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 3.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 12.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 6.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 90.1 MB/s eta 0:00:00
  Created wheel for hnswlib: filename=hnswlib-0.8.0-cp311-cp311-lin

# Step 2. Generate text embeddings

In [5]:
from sentence_transformers import SentenceTransformer
import numpy as np

model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

texts = ["IBM AI is revolutionizing enterprise search.", "HNSW accelerates nearest neighbor search."]

# Convert texts to vector embeddings
embeddings = model.encode(texts, normalize_embeddings=True)

print(embeddings)

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

[[-3.65254469e-02 -7.99229927e-03  6.41728938e-03 -5.85934427e-03
   1.39750922e-02  2.98918113e-02 -1.31787769e-02  4.51742969e-02
   2.99195088e-02 -5.72232483e-03 -2.91735083e-02  9.38772038e-02
   4.67104726e-02 -3.41732912e-02  9.17373132e-03  3.80207822e-02
   1.34376865e-02 -2.66106743e-02 -4.74588722e-02 -8.61497149e-02
  -3.55490372e-02 -4.36123228e-03  9.00632236e-03 -7.51922131e-02
  -2.36185966e-03  1.97391585e-03 -4.30914387e-03 -9.28533673e-02
  -1.79645568e-02 -1.29221044e-02 -3.78283975e-03  5.22588119e-02
   7.03847259e-02  1.05459042e-01 -1.50338477e-02 -2.51274910e-02
  -1.63155813e-02 -3.98926735e-02  9.52176228e-02 -5.35676964e-02
  -7.50523992e-03 -4.23889756e-02 -4.39065248e-02 -4.39310782e-02
   6.79444298e-02  3.59643847e-02 -5.33229783e-02 -6.61889091e-02
   5.74052110e-02  1.00460220e-02 -1.43828332e-01 -4.39385921e-02
   4.44049314e-02 -2.02398114e-02 -6.27250411e-03  1.91342626e-02
   2.90670041e-02  2.34574489e-02 -1.84675748e-03 -3.78104784e-02
   2.52358

# Step 3. Build an HNSW index

In [6]:
import hnswlib

print(type(embeddings))
dim = embeddings.shape[1]
print(f"Dimension: {dim}")
num_elements = len(embeddings)
print(f"Number of elements: {num_elements}")
# Initialize the HNSW index
p = hnswlib.Index(space="cosine", dim=dim)
p.init_index(max_elements=num_elements, ef_construction=200, M=16)
p.add_items(embeddings, np.arange(num_elements))

# Save the index for future use
p.save_index("rag_hnsw_index.bin")

<class 'numpy.ndarray'>
Dimension: 384
Number of elements: 2


# Step 4. Perform fast retrieval

In [ ]:
# Load the index
p.load_index("rag_hnsw_index.bin")

# Querying the system
query_text = "How does IBM use AI?"
query_embedding = model.encode([query_text], normalize_embeddings=True)
print(query_embedding)

# Retrieve nearest neighbors
labels, distances = p.knn_query(query_embedding, k=2)

print(f"Nearest neighbors' labels: {labels}")
print(f"\nDistance: {distances}")

# Print retrieved results
print(f"Retrieved documents: {[texts[i] for i in labels[0]]}")

[[-5.21683730e-02 -3.16497758e-02 -3.77699062e-02 -3.15785296e-02
   8.13558418e-03  1.44133046e-02  6.45040795e-02  6.36168122e-02
   6.92753494e-02  2.16417257e-02 -2.22964697e-02  4.87179346e-02
   5.12911230e-02 -4.84458469e-02 -1.09151369e-02  4.81496230e-02
   1.88993979e-02 -3.08694057e-02 -5.38474396e-02 -1.20192774e-01
   2.14587841e-02 -5.14495522e-02 -4.12315987e-02 -7.14637414e-02
   5.02772853e-02  4.19507511e-02  9.41789243e-03 -4.62466851e-02
   4.80913334e-02  2.32995041e-02  1.49522685e-02  2.04019602e-02
   7.95369819e-02  2.41217520e-02 -7.26110265e-02  2.54120994e-02
   6.75193872e-03 -6.33650571e-02  5.22584990e-02 -3.85624617e-02
  -6.47022128e-02 -5.52375801e-02  1.48057370e-02 -3.80330272e-02
   1.05601549e-01  4.76775691e-02 -5.69263548e-02 -3.20090801e-02
   2.45777015e-02  7.36787403e-03 -1.57652140e-01 -7.51282042e-03
   7.90659338e-02 -3.19029088e-04 -2.30940282e-02  4.00263481e-02
   2.83244457e-02  7.33153224e-02  3.02290777e-03 -2.99798138e-02
  -1.21620

# Misc. Numpy arrays

In [2]:
import numpy as np

a_1d = np.arange(3)
print(a_1d)
print(a_1d.ndim)
print(type(a_1d.ndim))
print(a_1d.shape)
print(type(a_1d.shape))
print(a_1d.size)
print(type(a_1d.size))
print(len(a_1d))
print(a_1d.shape[0])
print(a_1d.size)

[0 1 2]
1
<class 'int'>
(3,)
<class 'tuple'>
3
<class 'int'>
3
3
3


In [3]:
a_2d = np.arange(12).reshape((3, 4))
print(a_2d)
print(a_2d.ndim)
print(a_2d.shape)
print(a_2d.shape[0])
print(a_2d.shape[1])
row, col = a_2d.shape
print(row)
print(col)
print(a_2d.size)
print(len(a_2d))
print(a_2d.shape[0])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2
(3, 4)
3
4
3
4
12
3
3


In [ ]:
a_3d = np.arange(24).reshape((2, 3, 4))
print(a_3d)
print(a_3d.ndim)
print(a_3d.shape)
print(a_3d.size)
print(len(a_3d))
print(a_3d.shape[0])